// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ManagementDBContext))]
    [Migration("20260829065519_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.DefinitionVersionLog", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Key", "Version")
                        .IsUnique();

                    b.ToTable("DefinitionVersionLogs", (string)null);
                });

            modelBuilder.Entity("Domain.EntityDomain.Component.AIDefinition", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("AggroRadius")
                        .HasColumnType("real");

                    b.Property<float>("AttackRange")
                        .HasColumnType("real");

                    b.Property<string>("EntityDefinitionID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EquippedItemDefinitionID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAIControlled")
                        .HasColumnType("bit");

                    b.Property<float>("LeashDistance")
                        .HasColumnType("real");

                    b.Property<float>("ThinkInterval")
                        .HasColumnType("real");

                    b.HasKey("ID");

                    b.HasIndex("EntityDefinitionID")
                        .IsUnique();

                    b.HasIndex("IsAIControlled");

                    b.ToTable("AIDefinitions", (string)null);
                });

            modelBuilder.Entity("Domain.EntityDomain.Component.AppearanceDefinition", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityDefinitionID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SkinID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("EntityDefinitionID")
                        .IsUnique();

                    b.HasIndex("SkinID");

                    b.ToTable("AppearanceDefinitions", (string)null);
                });

            modelBuilder.Entity("Domain.EntityDomain.Component.AttributeGrowthValue", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AttributeValueID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("GrowthValue")
                        .HasColumnType("real");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("AttributeValueID");

                    b.HasIndex("AttributeValueID", "Level")
                        .IsUnique();

                    b.ToTable("AttributeGrowthValues", (string)null);
                });

            modelBuilder.Entity("Domain.EntityDomain.Component.AttributeValue", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("BaseValue")
                        .HasColumnType("real");

                    b.Property<Guid>("CharacteristicDefinitionID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Max")
                        .HasColumnType("real");

                    b.Property<float>("Min")
                        .HasColumnType("real");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("CharacteristicDefinitionID");

                    b.HasIndex("Type");

                    b.ToTable("AttributeValues", (string)null);
                });

            modelBuilder.Entity("Domain.EntityDomain.Component.CharacteristicDefinition", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityDefinitionID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("EntityDefinitionID")
                        .IsUnique();

                    b.ToTable("CharacteristicDefinitions", (string)null);
                });

            modelBuilder.Entity("Domain.EntityDomain.Component.CollisionDefinition", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CollisionRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityDefinitionID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("Height")
                        .HasColumnType("real");

                    b.Property<bool>("IsBlocking")
                        .HasColumnType("bit");

                    b.Property<string>("Layer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mask")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("OffsetX")
                        .HasColumnType("real");

                    b.Property<float>("OffsetY")
                        .HasColumnType("real");

                    b.Property<float>("Radius")
                        .HasColumnType("real");

                    b.Property<string>("ShapeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("Width")
                        .HasColumnType("real");

                    b.HasKey("ID");

                    b.HasIndex("EntityDefinitionID")
                        .IsUnique();

                    b.HasIndex("IsBlocking");

                    b.HasIndex("ShapeType");

                    b.ToTable("CollisionDefinitions", (string)null);
                });

            modelBuilder.Entity("Domain.EntityDomain.Component.InventoryDefinition", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityDefinitionID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SlotCount")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("EntityDefinitionID")
                        .IsUnique();

                    b.ToTable("InventoryDefinitions", (string)null);
                });

            modelBuilder.Entity("Domain.EntityDomain.Component.InventoryEntry", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("DefinitionID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("InventoryDefinitionID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Quality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("DefinitionID");

                    b.HasIndex("InventoryDefinitionID");

                    b.ToTable("InventoryEntries", (string)null);
                });

            modelBuilder.Entity("Domain.EntityDomain.Component.LifetimeDefinition", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Duration")
                        .HasColumnType("real");

                    b.Property<string>("EntityDefinitionID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("Duration");

                    b.HasIndex("EntityDefinitionID")
                        .IsUnique();

                    b.ToTable("LifetimeDefinitions", (string)null);
                });

            modelBuilder.Entity("Domain.EntityDomain.Component.ProjectileDefinition", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityDefinitionID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OnImpactSpawnEntityDefinitionID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Velocity")
                        .HasColumnType("real");

                    b.HasKey("ID");

                    b.HasIndex("EntityDefinitionID")
                        .IsUnique();

                    b.HasIndex("Velocity");

                    b.ToTable("ProjectileDefinitions", (string)null);
                });

            modelBuilder.Entity("Domain.EntityDomain.Component.TriggeredEffectDefinition", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EffectDefinitionIDs")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityDefinitionID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("EntityDefinitionID")
                        .IsUnique();

                    b.ToTable("TriggeredEffectDefinitions", (string)null);
                });

            modelBuilder.Entity("Domain.EntityDomain.EntityDefinition", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("EntityDefinitions", (string)null);
                });

            modelBuilder.Entity("Domain.IdentityDomain.User", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("Dob")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SteamID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("SteamID")
                        .IsUnique()
                        .HasFilter("[SteamID] IS NOT NULL");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Domain.LocalizationDomain.Locale", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.HasIndex("Code");

                    b.HasIndex("IsEnabled");

                    b.ToTable("Locales", (string)null);
                });

            modelBuilder.Entity("Domain.LocalizationDomain.LocalizationEntry", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LocaleCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("Key");

                    b.HasIndex("LocaleCode");

                    b.HasIndex("Key", "LocaleCode")
                        .IsUnique();

                    b.ToTable("LocalizationEntries", (string)null);
                });

            modelBuilder.Entity("Domain.MetaDomain.EffectDefinition", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AttributeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<float?>("Duration")
                        .HasColumnType("real");

                    b.Property<float?>("Interval")
                        .HasColumnType("real");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("Value")
                        .HasColumnType("real");

                    b.HasKey("ID");

                    b.HasIndex("AttributeType");

                    b.HasIndex("Type");

                    b.ToTable("EffectDefinitions", (string)null);
                });

            modelBuilder.Entity("Domain.MetaDomain.ItemDefinition", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("MaxDurability")
                        .HasColumnType("int");

                    b.Property<int?>("MaxStack")
                        .HasColumnType("int");

                    b.Property<string>("TriggeredAction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("Category");

                    b.HasIndex("Type");

                    b.ToTable("ItemDefinitions", (string)null);
                });

            modelBuilder.Entity("Domain.WorldDomain.Cell", b =>
                {
                    b.Property<string>("RoomDefinitionID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("X")
                        .HasColumnType("int");

                    b.Property<int>("Y")
                        .HasColumnType("int");

                    b.Property<int>("Z")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoomDefinitionID", "X", "Y", "Z");

                    b.HasIndex("RoomDefinitionID", "X", "Y", "Z")
                        .IsUnique();

                    b.ToTable("Cells", (string)null);
                });

            modelBuilder.Entity("Domain.WorldDomain.CombatRunDefinition", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("ID");

                    b.ToTable("CombatRunDefinitions", (string)null);
                });

            modelBuilder.Entity("Domain.WorldDomain.EntitySpawnRule", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityDefinitionID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MaxCount")
                        .HasColumnType("int");

                    b.Property<int>("MaxX")
                        .HasColumnType("int");

                    b.Property<int>("MaxY")
                        .HasColumnType("int");

                    b.Property<int>("MinCount")
                        .HasColumnType("int");

                    b.Property<int>("MinX")
                        .HasColumnType("int");

                    b.Property<int>("MinY")
                        .HasColumnType("int");

                    b.Property<string>("RoomDefinitionID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("EntityDefinitionID");

                    b.HasIndex("RoomDefinitionID");

                    b.ToTable("EntitySpawnRules", (string)null);
                });

            modelBuilder.Entity("Domain.WorldDomain.Floor", b =>
                {
                    b.Property<string>("CombatRunDefinitionID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("RoomDefinitionID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CombatRunDefinitionID", "Level");

                    b.HasIndex("Level");

                    b.HasIndex("RoomDefinitionID");

                    b.ToTable("CombatRunFloors", (string)null);
                });

            modelBuilder.Entity("Domain.WorldDomain.RoomDefinition", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("RoomDefinitions", (string)null);
                });

            modelBuilder.Entity("Domain.EntityDomain.Component.AppearanceDefinition", b =>
                {
                    b.OwnsOne("Contract.Common.HSV", "SkinColor", b1 =>
                        {
                            b1.Property<Guid>("AppearanceDefinitionID")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<float>("H")
                                .HasColumnType("real");

                            b1.Property<float>("S")
                                .HasColumnType("real");

                            b1.Property<float>("V")
                                .HasColumnType("real");

                            b1.HasKey("AppearanceDefinitionID");

                            b1.ToTable("AppearanceDefinitions");

                            b1.WithOwner()
                                .HasForeignKey("AppearanceDefinitionID");
                        });

                    b.Navigation("SkinColor")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.EntityDomain.Component.AttributeGrowthValue", b =>
                {
                    b.HasOne("Domain.EntityDomain.Component.AttributeValue", "AttributeValue")
                        .WithMany("AttributeGrowthValues")
                        .HasForeignKey("AttributeValueID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttributeValue");
                });

            modelBuilder.Entity("Domain.EntityDomain.Component.AttributeValue", b =>
                {
                    b.HasOne("Domain.EntityDomain.Component.CharacteristicDefinition", "CharacteristicDefinition")
                        .WithMany("AttributeValues")
                        .HasForeignKey("CharacteristicDefinitionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CharacteristicDefinition");
                });

            modelBuilder.Entity("Domain.EntityDomain.Component.InventoryEntry", b =>
                {
                    b.HasOne("Domain.EntityDomain.Component.InventoryDefinition", "InventoryDefinition")
                        .WithMany("DefaultItems")
                        .HasForeignKey("InventoryDefinitionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryDefinition");
                });

            modelBuilder.Entity("Domain.EntityDomain.EntityDefinition", b =>
                {
                    b.OwnsOne("Domain.EntityDomain.EntityPresentationDefinition", "Presentation", b1 =>
                        {
                            b1.Property<string>("EntityDefinitionID")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("IconID")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("EntityDefinitionID");

                            b1.ToTable("EntityDefinitions");

                            b1.WithOwner()
                                .HasForeignKey("EntityDefinitionID");

                            b1.OwnsOne("Domain.LocalizationDomain.LocalizedText", "LocalizedText", b2 =>
                                {
                                    b2.Property<string>("EntityPresentationDefinitionEntityDefinitionID")
                                        .HasColumnType("nvarchar(450)");

                                    b2.Property<string>("DescriptionKey")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("NameKey")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("EntityPresentationDefinitionEntityDefinitionID");

                                    b2.ToTable("EntityDefinitions");

                                    b2.WithOwner()
                                        .HasForeignKey("EntityPresentationDefinitionEntityDefinitionID");
                                });

                            b1.Navigation("LocalizedText")
                                .IsRequired();
                        });

                    b.Navigation("Presentation")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.LocalizationDomain.LocalizationEntry", b =>
                {
                    b.HasOne("Domain.LocalizationDomain.Locale", "Locale")
                        .WithMany("LocalizationEntries")
                        .HasForeignKey("LocaleCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Locale");
                });

            modelBuilder.Entity("Domain.MetaDomain.EffectDefinition", b =>
                {
                    b.OwnsOne("Domain.MetaDomain.EffectPresentationDefinition", "Presentation", b1 =>
                        {
                            b1.Property<string>("EffectDefinitionID")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("IconID")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("EffectDefinitionID");

                            b1.ToTable("EffectDefinitions");

                            b1.WithOwner()
                                .HasForeignKey("EffectDefinitionID");

                            b1.OwnsOne("Domain.LocalizationDomain.LocalizedText", "LocalizedText", b2 =>
                                {
                                    b2.Property<string>("EffectPresentationDefinitionEffectDefinitionID")
                                        .HasColumnType("nvarchar(450)");

                                    b2.Property<string>("DescriptionKey")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("NameKey")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("EffectPresentationDefinitionEffectDefinitionID");

                                    b2.ToTable("EffectDefinitions");

                                    b2.WithOwner()
                                        .HasForeignKey("EffectPresentationDefinitionEffectDefinitionID");
                                });

                            b1.Navigation("LocalizedText")
                                .IsRequired();
                        });

                    b.Navigation("Presentation")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.MetaDomain.ItemDefinition", b =>
                {
                    b.OwnsOne("Domain.MetaDomain.ConsumableConfig", "ConsumableConfig", b1 =>
                        {
                            b1.Property<string>("ItemDefinitionID")
                                .HasColumnType("nvarchar(450)");

                            b1.PrimitiveCollection<string>("EffectDefinitionIDs")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ItemDefinitionID");

                            b1.ToTable("ItemDefinitions");

                            b1
                                .ToJson("ConsumableConfig")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("ItemDefinitionID");
                        });

                    b.OwnsOne("Domain.MetaDomain.CostConfig", "CostConfig", b1 =>
                        {
                            b1.Property<string>("ItemDefinitionID")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("Method")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ItemDefinitionID");

                            b1.ToTable("ItemDefinitions");

                            b1.WithOwner()
                                .HasForeignKey("ItemDefinitionID");
                        });

                    b.OwnsOne("Domain.MetaDomain.EquippableConfig", "EquippableConfig", b1 =>
                        {
                            b1.Property<string>("ItemDefinitionID")
                                .HasColumnType("nvarchar(450)");

                            b1.PrimitiveCollection<string>("EffectDefinitionIDs")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Slot")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ItemDefinitionID");

                            b1.ToTable("ItemDefinitions");

                            b1
                                .ToJson("EquippableConfig")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("ItemDefinitionID");
                        });

                    b.OwnsOne("Domain.MetaDomain.ItemPresentationDefinition", "Presentation", b1 =>
                        {
                            b1.Property<string>("ItemDefinitionID")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("IconID")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ItemDefinitionID");

                            b1.ToTable("ItemDefinitions");

                            b1.WithOwner()
                                .HasForeignKey("ItemDefinitionID");

                            b1.OwnsOne("Domain.LocalizationDomain.LocalizedText", "LocalizedText", b2 =>
                                {
                                    b2.Property<string>("ItemPresentationDefinitionItemDefinitionID")
                                        .HasColumnType("nvarchar(450)");

                                    b2.Property<string>("DescriptionKey")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("NameKey")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("ItemPresentationDefinitionItemDefinitionID");

                                    b2.ToTable("ItemDefinitions");

                                    b2.WithOwner()
                                        .HasForeignKey("ItemPresentationDefinitionItemDefinitionID");
                                });

                            b1.Navigation("LocalizedText")
                                .IsRequired();
                        });

                    b.OwnsOne("Domain.MetaDomain.MeleeConfig", "MeleeConfig", b1 =>
                        {
                            b1.Property<string>("ItemDefinitionID")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("EntityDefinitionID")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ItemDefinitionID");

                            b1.ToTable("ItemDefinitions");

                            b1.WithOwner()
                                .HasForeignKey("ItemDefinitionID");
                        });

                    b.OwnsOne("Domain.MetaDomain.PlaceableConfig", "PlaceableConfig", b1 =>
                        {
                            b1.Property<string>("ItemDefinitionID")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("EntityDefinitionID")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ItemDefinitionID");

                            b1.ToTable("ItemDefinitions");

                            b1.WithOwner()
                                .HasForeignKey("ItemDefinitionID");
                        });

                    b.OwnsOne("Domain.MetaDomain.RangedConfig", "RangedConfig", b1 =>
                        {
                            b1.Property<string>("ItemDefinitionID")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("EntityDefinitionID")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ItemDefinitionID");

                            b1.ToTable("ItemDefinitions");

                            b1.WithOwner()
                                .HasForeignKey("ItemDefinitionID");
                        });

                    b.Navigation("ConsumableConfig");

                    b.Navigation("CostConfig")
                        .IsRequired();

                    b.Navigation("EquippableConfig");

                    b.Navigation("MeleeConfig");

                    b.Navigation("PlaceableConfig");

                    b.Navigation("Presentation")
                        .IsRequired();

                    b.Navigation("RangedConfig");
                });

            modelBuilder.Entity("Domain.WorldDomain.Cell", b =>
                {
                    b.HasOne("Domain.WorldDomain.RoomDefinition", "RoomDefinition")
                        .WithMany("Cells")
                        .HasForeignKey("RoomDefinitionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoomDefinition");
                });

            modelBuilder.Entity("Domain.WorldDomain.EntitySpawnRule", b =>
                {
                    b.HasOne("Domain.EntityDomain.EntityDefinition", "EntityDefinition")
                        .WithMany()
                        .HasForeignKey("EntityDefinitionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.WorldDomain.RoomDefinition", "RoomDefinition")
                        .WithMany("EntitySpawnRules")
                        .HasForeignKey("RoomDefinitionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntityDefinition");

                    b.Navigation("RoomDefinition");
                });

            modelBuilder.Entity("Domain.WorldDomain.Floor", b =>
                {
                    b.HasOne("Domain.WorldDomain.CombatRunDefinition", "CombatRunDefinition")
                        .WithMany("Floors")
                        .HasForeignKey("CombatRunDefinitionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CombatRunDefinition");
                });

            modelBuilder.Entity("Domain.WorldDomain.RoomDefinition", b =>
                {
                    b.OwnsOne("Domain.WorldDomain.RoomPresentationDefinition", "Presentation", b1 =>
                        {
                            b1.Property<string>("RoomDefinitionID")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<string>("IconID")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("RoomDefinitionID");

                            b1.ToTable("RoomDefinitions");

                            b1.WithOwner()
                                .HasForeignKey("RoomDefinitionID");

                            b1.OwnsOne("Domain.LocalizationDomain.LocalizedText", "LocalizedText", b2 =>
                                {
                                    b2.Property<string>("RoomPresentationDefinitionRoomDefinitionID")
                                        .HasColumnType("nvarchar(450)");

                                    b2.Property<string>("DescriptionKey")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("NameKey")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("RoomPresentationDefinitionRoomDefinitionID");

                                    b2.ToTable("RoomDefinitions");

                                    b2.WithOwner()
                                        .HasForeignKey("RoomPresentationDefinitionRoomDefinitionID");
                                });

                            b1.Navigation("LocalizedText")
                                .IsRequired();
                        });

                    b.Navigation("Presentation")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.EntityDomain.Component.AttributeValue", b =>
                {
                    b.Navigation("AttributeGrowthValues");
                });

            modelBuilder.Entity("Domain.EntityDomain.Component.CharacteristicDefinition", b =>
                {
                    b.Navigation("AttributeValues");
                });

            modelBuilder.Entity("Domain.EntityDomain.Component.InventoryDefinition", b =>
                {
                    b.Navigation("DefaultItems");
                });

            modelBuilder.Entity("Domain.LocalizationDomain.Locale", b =>
                {
                    b.Navigation("LocalizationEntries");
                });

            modelBuilder.Entity("Domain.WorldDomain.CombatRunDefinition", b =>
                {
                    b.Navigation("Floors");
                });

            modelBuilder.Entity("Domain.WorldDomain.RoomDefinition", b =>
                {
                    b.Navigation("Cells");

                    b.Navigation("EntitySpawnRules");
                });
#pragma warning restore 612, 618
        }
    }
}
